version: 2

orbs:
  circleci-maven-release-orb: sonatype-nexus-community/circleci-maven-release-orb@0.0.15

references:
  test_library: &test_library
    run:
      name: Test
      command: |
        export TERM=${TERM:-dumb}
        ./install_crypto_deps.sh
        ./gradlew test

  save_test_results: &save_test_results
    run:
      name: Save test results
      command: |
        mkdir -p ~/junit
        find . -type f -regex "$OUT_DIR/build/test-results/test/.*xml" -exec cp {} ~/junit/ \;
      when: always

  default_test_job: &default_test_job
    parallelism: 1
    steps:
      - checkout
      - *test_library
      - *save_test_results
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit

jobs:
  test_library_jdk7:
    <<: *default_test_job
    docker:
      - image: openjdk:7

  test_library_jdk8:
    <<: *default_test_job
    docker:
      - image: openjdk:8

  test_library_jdk9:
    <<: *default_test_job
    docker:
      - image: openjdk:9

workflows:
  version: 2

  build:
    jobs:
      - test_library_jdk7
      - test_library_jdk8
      - test_library_jdk9

  release-master:
    jobs:
      - approve-release:
          type: approval
          filters:
            branches:
              only: master
      - circleci-maven-release-orb/run-maven-release:
          requires:
            - approve-release
          ssh-fingerprints: "60:a1:dc:aa:6a:40:00:84:11:47:ca:e1:b7:73:fd:93"
          filters:
            branches:
              only: master

