name: Release

on:
  push:
    branches: [master]

jobs:
  release:
    if: "!contains(github.event.head_commit.message, 'chore: prepare release')"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.GOCARDLESS_CI_ROBOT_TOKEN }}
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - uses: gocardless/github-actions/proxies/knope-dev-action@master
        with:
          version: 0.23.0
      - run: knope release --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GOCARDLESS_CI_ROBOT_TOKEN }}
        continue-on-error: true
